export const EMPLOYER_REGISTRATION_REQUEST = "EMPLOYER_REGISTRATION_REQUEST";
export const EMPLOYER_REGISTRATION_SUCCESS = "EMPLOYER_REGISTRATION_SUCCESS";
export const EMPLOYER_REGISTRATION_FAILED = "EMPLOYER_REGISTRATION_FAILED";

export const GET_EMPLOYER_PROFILE_REQUEST = "GET_EMPLOYER_PROFILE_REQUEST";
export const GET_EMPLOYER_PROFILE_SUCCESS = "GET_EMPLOYER_PROFILE_SUCCESS";
export const GET_EMPLOYER_PROFILE_FAILED = "GET_EMPLOYER_PROFILE_FAILED";

export const EDIT_EMPLOYER_REQUEST = "EDIT_EMPLOYER_REQUEST";
export const EDIT_EMPLOYER_SUCCESS = "EDIT_EMPLOYER_SUCCESS";
export const EDIT_EMPLOYER_FAILED = "EDIT_EMPLOYER_FAILED";

export const EMPLOYER_DETAILS_RESET = "EMPLOYER_DETAILS_RESET";
