export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILED = "GET_ALL_POST_FAILED";

export const GET_ADVANCED_POST_REQUEST = "GET_ADVANCED_POST_REQUEST";
export const GET_ADVANCED_POST_SUCCESS = "GET_ADVANCED_POST_SUCCESS";
export const GET_ADVANCED_POST_FAILED = "GET_ADVANCED_POST_FAILED";

export const GET_CATEGORY_POST_REQUEST = "GET_CATEGORY_POST_REQUEST";
export const GET_CATEGORY_POST_SUCCESS = "GET_CATEGORY_POST_SUCCESS";
export const GET_CATEGORY_POST_FAILED = "GET_CATEGORY_POST_FAILED";

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST";
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS";
export const GET_POST_DETAILS_FAILED = "GET_POST_DETAILS_FAILED";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILED = "POST_CREATE_FAILED";

export const POST_EDIT_REQUEST = "POST_EDIT_REQUEST";
export const POST_EDIT_SUCCESS = "POST_EDIT_SUCCESS";
export const POST_EDIT_FAILED = "POST_EDIT_FAILED";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAILED = "POST_DELETE_FAILED";

export const POST_PAID_PROPOSAL_REQUEST = "POST_PAID_PROPOSAL_REQUEST";
export const POST_PAID_PROPOSAL_SUCCESS = "POST_PAID_PROPOSAL_SUCCESS";
export const POST_PAID_PROPOSAL_FAILED = "POST_PAID_PROPOSAL_FAILED";

export const POST_ACCEPT_PROPOSAL_REQUEST = "POST_ACCEPT_PROPOSAL_REQUEST";
export const POST_ACCEPT_PROPOSAL_SUCCESS = "POST_ACCEPT_PROPOSAL_SUCCESS";
export const POST_ACCEPT_PROPOSAL_FAILED = "POST_ACCEPT_PROPOSAL_FAILED";

export const POST_FINISH_PROPOSAL_REQUEST = "POST_FINISH_PROPOSAL_REQUEST";
export const POST_FINISH_PROPOSAL_SUCCESS = "POST_FINISH_PROPOSAL_SUCCESS";
export const POST_FINISH_PROPOSAL_FAILED = "POST_FINISH_PROPOSAL_FAILED";
