export const TALENT_REGISTRATION_REQUEST = "TALENT_REGISTRATION_REQUEST";
export const TALENT_REGISTRATION_SUCCESS = "TALENT_REGISTRATION_SUCCESS";
export const TALENT_REGISTRATION_FAILED = "TALENT_REGISTRATION_FAILED";

export const GET_TALENT_PROFILE_REQUEST = "GET_TALENT_PROFILE_REQUEST";
export const GET_TALENT_PROFILE_SUCCESS = "GET_TALENT_PROFILE_SUCCESS";
export const GET_TALENT_PROFILE_FAILED = "GET_TALENT_PROFILE_FAILED";

export const EDIT_TALENT_REQUEST = "EDIT_TALENT_REQUEST";
export const EDIT_TALENT_SUCCESS = "EDIT_TALENT_SUCCESS";
export const EDIT_TALENT_FAILED = "EDIT_TALENT_FAILED";

export const CREATE_TALENT_BIDS_REQUEST = "CREATE_TALENT_BIDS_REQUEST";
export const CREATE_TALENT_BIDS_SUCCESS = "CREATE_TALENT_BIDS_SUCCESS";
export const CREATE_TALENT_BIDS_FAILED = "CREATE_TALENT_BIDS_FAILED";

export const EDIT_TALENT_BIDS_REQUEST = "EDIT_TALENT_BIDS_REQUEST";
export const EDIT_TALENT_BIDS_SUCCESS = "EDIT_TALENT_BIDS_SUCCESS";
export const EDIT_TALENT_BIDS_FAILED = "EDIT_TALENT_BIDS_FAILED";

export const DELETE_TALENT_BIDS_REQUEST = "DELETE_TALENT_BIDS_REQUEST";
export const DELETE_TALENT_BIDS_SUCCESS = "DELETE_TALENT_BIDS_SUCCESS";
export const DELETE_TALENT_BIDS_FAILED = "DELETE_TALENT_BIDS_FAILED";

export const TALENT_DETAILS_RESET = "TALENT_DETAILS_RESET";
