export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const USER_RESETPW_REQUEST = "USER_RESETPW_REQUEST";
export const USER_RESETPW_SUCCESS = "USER_RESETPW_SUCCESS";
export const USER_RESETPW_FAILED = "USER_RESETPW_FAILED";

export const USER_VERIFY_OTP_REQUEST = "USER_VERIFY_OTP_REQUEST";
export const USER_VERIFY_OTP_SUCCESS = "USER_VERIFY_OTP_SUCCESS";
export const USER_VERIFY_OTP_FAILED = "USER_VERIFY_OTP_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";
